version: '3.8'

services:
  red-app:
    image: trafficlight/red:v1.0
    container_name: red-app
    networks:
      - traffic-light

  yellow-app:
    image: trafficlight/yellow:v1.0
    container_name: yellow-app
    networks:
      - traffic-light

  green-app:
    image: trafficlight/green:v1.0
    container_name: green-app
    networks:
      - traffic-light

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "3000:3000"
      - "4000:4000"
      - "5000:5000"
    depends_on:
      - red-app
      - yellow-app
      - green-app
    networks:
      - traffic-light

networks:
  traffic-light:
